"""Merged tests: test_feat033_notation, test_feat035_nesting."""

from __future__ import annotations

import dataclasses
from typing import ClassVar

import pytest
from pydantic import BaseModel, ValidationError

import pyarchi
from pyarchi.enums import RelationshipCategory
from pyarchi.metamodel.concepts import (
    Concept,
    Element,
    Relationship,
    RelationshipConnector,
)
from pyarchi.metamodel.notation import NotationMetadata


class TestNotationMetadataInstantiation:
    """NotationMetadata can be instantiated with all three fields."""

    def test_instantiate_with_all_fields(self) -> None:
        nm = NotationMetadata(
            corner_shape="square",
            layer_color="#FFFFB5",
            badge_letter="A",
        )
        assert nm.corner_shape == "square"
        assert nm.layer_color == "#FFFFB5"
        assert nm.badge_letter == "A"

    def test_badge_letter_none_is_valid(self) -> None:
        """badge_letter=None is valid for element types without a letter badge."""
        nm = NotationMetadata(
            corner_shape="round",
            layer_color="#B5FFFF",
            badge_letter=None,
        )
        assert nm.badge_letter is None


class TestNotationMetadataFrozen:
    """frozen=True prevents mutation (raises FrozenInstanceError)."""

    def test_cannot_assign_corner_shape(self) -> None:
        nm = NotationMetadata(
            corner_shape="square",
            layer_color="#FFFFB5",
            badge_letter=None,
        )
        with pytest.raises(dataclasses.FrozenInstanceError):
            nm.corner_shape = "round"  # type: ignore[misc]

    def test_cannot_assign_layer_color(self) -> None:
        nm = NotationMetadata(
            corner_shape="square",
            layer_color="#FFFFB5",
            badge_letter=None,
        )
        with pytest.raises(dataclasses.FrozenInstanceError):
            nm.layer_color = "#000000"  # type: ignore[misc]

    def test_cannot_assign_badge_letter(self) -> None:
        nm = NotationMetadata(
            corner_shape="square",
            layer_color="#FFFFB5",
            badge_letter=None,
        )
        with pytest.raises(dataclasses.FrozenInstanceError):
            nm.badge_letter = "X"  # type: ignore[misc]


class TestNotationMetadataEquality:
    """Instances are equal when fields are equal (__eq__ generated by dataclass)."""

    def test_equal_instances(self) -> None:
        a = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter="A")
        b = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter="A")
        assert a == b

    def test_unequal_instances(self) -> None:
        a = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter="A")
        b = NotationMetadata(corner_shape="round", layer_color="#FFFFB5", badge_letter="A")
        assert a != b


class TestNotationMetadataHashable:
    """Instances are hashable because frozen=True generates __hash__."""

    def test_hashable(self) -> None:
        nm = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter=None)
        # If not hashable, this raises TypeError
        assert isinstance(hash(nm), int)

    def test_equal_instances_have_same_hash(self) -> None:
        a = NotationMetadata(corner_shape="cut", layer_color="#B5B5FF", badge_letter="S")
        b = NotationMetadata(corner_shape="cut", layer_color="#B5B5FF", badge_letter="S")
        assert hash(a) == hash(b)

    def test_usable_as_dict_key(self) -> None:
        nm = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter=None)
        d = {nm: "test"}
        assert d[nm] == "test"

    def test_usable_in_set(self) -> None:
        a = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter=None)
        b = NotationMetadata(corner_shape="square", layer_color="#FFFFB5", badge_letter=None)
        s = {a, b}
        assert len(s) == 1


class TestNotationMetadataTopLevelExport:
    """NotationMetadata is importable from pyarchi top-level."""

    def test_importable_from_pyarchi(self) -> None:
        from pyarchi import NotationMetadata as TopLevelNotationMetadata

        assert TopLevelNotationMetadata is NotationMetadata

    def test_in_pyarchi_all(self) -> None:
        """'NotationMetadata' appears in pyarchi.__all__."""
        assert "NotationMetadata" in pyarchi.__all__

    def test_hasattr_pyarchi(self) -> None:
        """hasattr(pyarchi, 'NotationMetadata') is True."""
        assert hasattr(pyarchi, "NotationMetadata")


class TestClassVarPattern:
    """Demonstrate that ClassVar[NotationMetadata] works on a Pydantic model.

    This validates STORY-03.3.2: the ClassVar pattern is viable for concrete
    element classes that will be defined in EPIC-004.  The test creates a
    minimal Pydantic BaseModel subclass with notation: ClassVar[NotationMetadata]
    and verifies that 'notation' does NOT appear in model_fields.
    """

    def test_classvar_excluded_from_model_fields(self) -> None:
        class _MockElement(BaseModel):
            """Minimal stand-in for a concrete Element subclass."""

            name: str
            notation: ClassVar[NotationMetadata] = NotationMetadata(
                corner_shape="square",
                layer_color="#FFFFB5",
                badge_letter=None,
            )

        assert "notation" not in _MockElement.model_fields

    def test_classvar_accessible_on_class(self) -> None:
        class _MockElement(BaseModel):
            name: str
            notation: ClassVar[NotationMetadata] = NotationMetadata(
                corner_shape="round",
                layer_color="#B5FFFF",
                badge_letter="S",
            )

        assert _MockElement.notation.corner_shape == "round"
        assert _MockElement.notation.layer_color == "#B5FFFF"
        assert _MockElement.notation.badge_letter == "S"

    def test_classvar_accessible_on_instance(self) -> None:
        class _MockElement(BaseModel):
            name: str
            notation: ClassVar[NotationMetadata] = NotationMetadata(
                corner_shape="cut",
                layer_color="#B5B5FF",
                badge_letter="F",
            )

        instance = _MockElement(name="test")
        assert instance.notation.corner_shape == "cut"
        assert instance.notation.badge_letter == "F"

    def test_classvar_not_in_model_dump(self) -> None:
        class _MockElement(BaseModel):
            name: str
            notation: ClassVar[NotationMetadata] = NotationMetadata(
                corner_shape="square",
                layer_color="#FFFFB5",
                badge_letter=None,
            )

        instance = _MockElement(name="test")
        dump = instance.model_dump()
        assert "notation" not in dump


# ---------------------------------------------------------------------------
# Test-local helpers: minimal concrete subclasses for testing extra="forbid"
# ---------------------------------------------------------------------------


class _StubElement(Element):
    """Minimal concrete Element for testing extra field rejection."""

    @property
    def _type_name(self) -> str:
        return "StubElement"


class _StubRelationship(Relationship):
    """Minimal concrete Relationship for testing extra field rejection."""

    category: ClassVar[RelationshipCategory] = RelationshipCategory.OTHER

    @property
    def _type_name(self) -> str:
        return "StubRelationship"


class _StubConnector(RelationshipConnector):
    """Minimal concrete RelationshipConnector for testing extra field rejection."""

    @property
    def _type_name(self) -> str:
        return "StubConnector"


# ---------------------------------------------------------------------------
# TestExtraForbidOnConcept -- immediately passing tests for STORY-03.5.2
# ---------------------------------------------------------------------------


class TestExtraForbidOnConcept:
    """Verify that extra="forbid" on Concept rejects unknown kwargs on all
    branches of the hierarchy.

    These tests validate STORY-03.5.2: the extra="forbid" change to
    Concept.model_config.  They are NOT xfail -- they must pass once the
    production code change is applied.
    """

    def test_element_rejects_unknown_kwarg(self) -> None:
        """Passing an unknown kwarg to a concrete Element raises ValidationError."""
        with pytest.raises(ValidationError):
            _StubElement(name="test", bogus_field=True)  # type: ignore[call-arg]

    def test_relationship_rejects_unknown_kwarg(self) -> None:
        """Passing an unknown kwarg to a concrete Relationship raises ValidationError."""
        source = _StubElement(name="src")
        target = _StubElement(name="tgt")
        with pytest.raises(ValidationError):
            _StubRelationship(
                name="test",
                source=source,
                target=target,
                bogus_field=True,  # type: ignore[call-arg]
            )

    def test_connector_rejects_unknown_kwarg(self) -> None:
        """Passing an unknown kwarg to a concrete RelationshipConnector raises ValidationError."""
        with pytest.raises(ValidationError):
            _StubConnector(bogus_field=True)  # type: ignore[call-arg]

    def test_element_rejects_is_nested_kwarg(self) -> None:
        """is_nested is not a field on Element; extra="forbid" rejects it."""
        with pytest.raises(ValidationError):
            _StubElement(name="test", is_nested=True)  # type: ignore[call-arg]

    def test_relationship_rejects_is_nested_kwarg(self) -> None:
        """is_nested is not a field on base Relationship; extra="forbid" rejects it.

        Once StructuralRelationship exists (EPIC-005), is_nested will be
        accepted on structural subclasses but still rejected on non-structural.
        """
        source = _StubElement(name="src")
        target = _StubElement(name="tgt")
        with pytest.raises(ValidationError):
            _StubRelationship(
                name="test",
                source=source,
                target=target,
                is_nested=True,  # type: ignore[call-arg]
            )

    def test_extra_forbid_in_concept_model_config(self) -> None:
        """Confirm extra="forbid" is set in Concept.model_config."""
        assert Concept.model_config.get("extra") == "forbid"


# ---------------------------------------------------------------------------
# TestIsNestedOnStructuralRelationship -- xfail until EPIC-005
# ---------------------------------------------------------------------------


class TestIsNestedOnStructuralRelationship:
    """Test that is_nested=True on Composition does not raise.

    Requires Composition class from EPIC-005 (FEAT-05.2).
    """

    def test_composition_accepts_is_nested_true(self) -> None:
        """Composition(is_nested=True) must not raise ValidationError."""
        from pyarchi import Composition

        source = _StubElement(name="whole")
        target = _StubElement(name="part")
        comp = Composition(name="nesting", source=source, target=target, is_nested=True)
        assert comp.is_nested is True

    def test_composition_is_nested_defaults_false(self) -> None:
        """Composition() without is_nested must default to False."""
        from pyarchi import Composition

        source = _StubElement(name="whole")
        target = _StubElement(name="part")
        comp = Composition(name="default", source=source, target=target)
        assert comp.is_nested is False


# ---------------------------------------------------------------------------
# TestIsNestedRejectedOnNonStructural -- xfail until EPIC-005
# ---------------------------------------------------------------------------


class TestIsNestedRejectedOnNonStructural:
    """Test that is_nested=True on Triggering raises ValidationError.

    Requires Triggering class from EPIC-005 (FEAT-05.7).
    """

    def test_triggering_rejects_is_nested(self) -> None:
        """Triggering(is_nested=True) must raise ValidationError."""
        from pyarchi import Triggering

        source = _StubElement(name="src")
        target = _StubElement(name="tgt")
        with pytest.raises(ValidationError):
            Triggering(
                name="bad",
                source=source,
                target=target,
                is_nested=True,
            )
